# =========================== 服务器配置 ===========================
server:
  port: ${SERVER_PORT:9206}
  ssl:
    enabled: @SSL-ENABLED@
    key-store: classpath:scg-keystore.p12
    key-alias: ${spring.application.name}
    key-store-type: PKCS12
    key-store-password: Zcx@223852//
  http2:
    enabled: @SSL-ENABLED@
  shutdown: graceful

# =========================== gRPC 配置 ===========================
grpc:
  server:
    port: ${SERVER_GRPC_PORT:6001}

# =========================== Spring 配置 ===========================
spring:
  application:
    # 应用名称
    name: @pom.parent.artifactId@
  profiles:
    # 环境配置
    active: @PROFILE-ACTIVE@
