name: lersosa-python-env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.11.11
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
