# =========================== 项目配置 ===========================
lersosa-version: ${lersosa.version}
spring-cloud-version: ${spring-cloud.version}
spring-cloud-alibaba-version: ${spring-cloud-alibaba.version}

# =========================== 服务器配置 ===========================
server:
  port: ${SERVER-PORT:9120}
  ssl:
    enabled: @SSL-ENABLED@
    key-store: classpath:scg-keystore.p12
    key-alias: ${spring.application.name}
    key-store-type: PKCS12
    key-store-password: Zcx@223852//
  http2:
    enabled: @SSL-ENABLED@
  shutdown: graceful

# =========================== Spring 配置 ===========================
spring:
  application:
    # 应用名称
    name: @pom.artifactId@
  profiles:
    # 环境配置
    active: @PROFILE-ACTIVE@
