# 安全配置
security:
  # 不校验白名单
  ignore:
    whites:
      - /python/*
      - /auth/code
      - /auth/logout
      - /auth/login
      - /auth/binding/*
      - /auth/social/callback
      - /auth/register
      - /auth/tenant/list
      - /resource/sms/code
      - /resource/sse/close
      - /doc/swagger-ui/*
      - /v3/api-docs/**
      - /*/v3/api-docs/**
      - /*/error
      - /csrf

spring:
  cloud:
    # 网关配置
    gateway:
      # 打印请求日志(自定义)
      requestLog: true
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: lersosa-service-auth
          uri: lb://lersosa-service-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        # 代码生成
        - id: lersosa-service-gen
          uri: lb://lersosa-service-gen
          predicates:
            - Path=/tool/**
          filters:
            - StripPrefix=1
        # 系统模块
        - id: lersosa-service-system
          uri: lb://lersosa-service-system
          predicates:
            - Path=/system/**,/monitor/**
          filters:
            - StripPrefix=1
        # 资源服务
        - id: lersosa-service-resource
          uri: lb://lersosa-service-resource
          predicates:
            - Path=/resource/**
          filters:
            - StripPrefix=1
        # workflow服务
        - id: lersosa-service-workflow
          uri: lb://lersosa-service-workflow
          predicates:
            - Path=/workflow/**
          filters:
            - StripPrefix=1
        # 演示服务
        - id: lersosa-service-demo
          uri: lb://lersosa-service-demo
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
        # MQ演示服务
        - id: lersosa-service-test-mq
          uri: lb://lersosa-service-test-mq
          predicates:
            - Path=/test-mq/**
          filters:
            - StripPrefix=1
        # pulsar 服务
        - id: lersosa-service-pulsar
          uri: lb://lersosa-service-pulsar
          predicates:
            - Path=/pulsar/**
          filters:
            - StripPrefix=1
        # python 服务
        - id: lersosa-service-python
          uri: lb://lersosa-service-python
          predicates:
            - Path=/python/**
          filters:
            - StripPrefix=1

    # sentinel 配置
    sentinel:
      filter:
        enabled: false
      # nacos配置持久化
      datasource:
        ds1:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            dataId: sentinel-${spring.application.name}.json
            groupId: ${spring.cloud.nacos.config.group}
            username: ${spring.cloud.nacos.username}
            password: ${spring.cloud.nacos.password}
            namespace: ${spring.profiles.active}
            data-type: json
            rule-type: gw-flow

  datasource:
    dynamic:
      primary: system-master
      strict: true
      p6spy: true
      seata: ${seata.enabled}
      hikari:
        maxPoolSize: 20
        minIdle: 10
        connectionTimeout: 30000
        validationTimeout: 5000
        idleTimeout: 600000
        maxLifetime: 1800000
        keepaliveTime: 30000
      datasource:
        system-master:
          url: ${datasource.system-master.url}
          username: ${datasource.system-master.username}
          password: ${datasource.system-master.password}
        gen:
          url: ${datasource.gen.url}
          username: ${datasource.gen.username}
          password: ${datasource.gen.password}
        job:
          url: ${datasource.job.url}
          username: ${datasource.job.username}
          password: ${datasource.job.password}
        workflow:
          url: ${datasource.workflow.url}
          username: ${datasource.workflow.username}
          password: ${datasource.workflow.password}
        sharding:
          url: ${datasource.sharding.url}
          username: ${datasource.sharding.username}
          password: ${datasource.sharding.password}

springdoc:
  api-docs:
    ignore:
      excludes:
        - lersosa-gateway-api
        - lersosa-service-job
        - lersosa-service-grpc
        - lersosa-service-workflow
